Project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from Tienda import views
from Tienda.views import home, registro , hombre, mujer, logout_view, contacto, compra
from django.conf.urls.static import static

# Importa DEBUG desde settings
DEBUG = settings.DEBUG
urlpatterns = [
    # Home y Admin el home incluye los productos
    path('', views.home, name = 'home'),
    path('admin/', admin.site.urls),
    path('contacto/', contacto, name="contacto"),
    # Vistas de productos para hombre y mujer 
    path('hombre/', hombre, name="hombre"),
    path('mujer/', mujer, name="mujer"),
    # Registrase y Login
    path('accounts/', include('django.contrib.auth.urls')),
    path('registro/', registro, name="registro"),
    path('logout/', logout_view, name='logout'),
   # Comprar
    path('compra/', compra, name='compra'),
    
]
# Configuración para servir archivos de medios durante el desarrollo
if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Tienda/models.py
from django.contrib.auth.models import AbstractUser, User
from django.db import models

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Categoría'
        verbose_name_plural = 'Categorías'

class Producto(models.Model):
    GENERO_CHOICES = [
        ('H', 'Hombre'),
        ('M', 'Mujer'),
    ]

    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    categorias = models.ManyToManyField(Categoria)
    imagen = models.ImageField(upload_to='productos_images/', blank=True, null=True)
    genero = models.CharField(max_length=1, choices=GENERO_CHOICES, null=True, blank=True)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

class Pedido(models.Model):
    cliente = models.ForeignKey(User, on_delete=models.CASCADE)
    productos = models.ManyToManyField(Producto, through='DetallePedido')
    fecha_pedido = models.DateTimeField(auto_now_add=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0)  # Agregamos un valor predeterminado
    estimacion_entrega = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"Pedido #{self.id} - {self.cliente}"

    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'

class DetallePedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()

    def __str__(self):
        return f"Detalle de Pedido #{self.pedido.id} - {self.producto.nombre}"

    class Meta:
        verbose_name = 'Detalle de Pedido'
        verbose_name_plural = 'Detalles de Pedidos'

Tienda/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User 
        fields = ['username', "first_name", "last_name", "email", "password1", "password2"]

# forms.py
from django import forms

class CompraForm(forms.Form):
    cantidad = forms.IntegerField(min_value=1, label='Cantidad a comprar')
    # Puedes agregar más campos según tus necesidades (dirección de envío, etc.)

Tienda/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .models import Producto

def home(request):
    productos = Producto.objects.all()
    return render(request, 'Tienda/home.html', {'productos': productos})

def hombre(request):
    productos = Producto.objects.all()
    return render(request, 'ropa/hombre.html', {'productos': productos})

def mujer(request):
    productos = Producto.objects.all()
    return render(request, 'ropa/mujer.html', {'productos': productos})

def logout_view(request):
    logout(request)
    return render(request, 'Tienda/home.html')

def registro(request):
    data = {'form': CustomUserCreationForm()}

    if request.method == 'POST':
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data["username"], password=formulario.cleaned_data["password1"])
            login(request, user)
            messages.success(request, "Te has registrado correctamente")
            return redirect(to="home")
        data["form"] = formulario

    return render(request, 'registration/register.html', data)

def contacto(request):
    return render(request, 'Tienda/contacto.html')

def compra(request):
    if request.method == 'POST':
        messages.success(request, 'Compra realizada con éxito.')
        return redirect('home')
    # Resto del código si el método de solicitud no es POST
    return render(request, 'compra/compra.html')

Tienda/templates/Tienda/base.html
<!-- Nombre del Gestor de Base de datos -->
<!-- pgAdmin -->
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} | Ropa en Linea {% endblock %} </title>
    <link rel="stylesheet" href="{% static 'Tienda/css/estilos.css' %}">
    <link rel="stylesheet" href="{% static 'Tienda/css/productos.css' %}">
    {% block extra_styles %}{% endblock %}

</head>

<body>

    <header >
        <nav class="nav">

            <div class="logo">
                <a href="{% url 'home' %}">Fashion Style</a>
            </div>

            <div class="nav-menu">

                <input type="checkbox" id="check">
                <label for="check" class="checkbtn">
                    <i class="menu-icon">
                        <img src="{% static 'Tienda/img/menu.png' %}" alt="error">
                    </i>
                </label>
                <ul class="menu">
                    <li><a href="{% url 'home' %}">Inicio</a></li>
                    <li><a href="{% url 'hombre' %}">Hombres</a></li>
                    <li><a href="{% url 'mujer' %}">Mujer</a></li>
                    <li><a href="{% url 'contacto' %}">Contactos</a></li>

                    {% if user.is_authenticated %}

                    <li>
                        <a href="{% url 'logout' %}">Cerrar sesión</a>
                    </li>
                    <li>
                        <a href="#">@{{ user.username }}</a>
                    </li>
                    {% else %}

                    <li>
                        <a href="{% url 'login' %}">Iniciar sesión</a>
                    </li>

                    <li>
                        <a href="{% url 'registro' %}">Registrarse</a>
                    </li>
                    {% endif %}

                </ul>
            </div>

        </nav>
    </header>

    <!-- LLamada de la función para darle movimiento la etiqueta del nav -->
    <script src="{% static 'Tienda/js/menu.js' %}"></script>

    {% block content %} {% endblock %}

    <!-- Scrip que muestra una ventana cuando se registran -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% if messages %}
    {% for m in messages %}

    <script>
        Swal.fire({
            "title": "Felisitaciones",
            "text": "{{m}}",
            "icon": "success"
        })
    </script>
    {% endfor %}
    {% endif %}

    <!-- Pie de Pagina -->
    <footer class="pie">
        <div class="footer-container">
            <p>Creador: Ponce Macias Rafael</p>
            <p class="copyright"> &copy; Fashion Style 2023</p>
        </div>
    </footer>

</body>

</html>

Tienda/templates/Tienda/contacto.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contactos</title>
    <link rel="stylesheet" href="{% static 'Tienda/css/ropa.css' %}">
</head>

<style>
    body{
        font-family: Arial, Helvetica, sans-serif;
    }
</style>

<header>
    <nav class="nav">

        <div class="logo">
            <a class="fashion-style"  href="{% url 'home' %}">Fashion Style</a>
        </div>

        <div class="nav-menu">

            <input type="checkbox" id="check">
            <label for="check" class="checkbtn">
                <i class="menu-icon">
                    <img src="{% static 'Tienda/img/menu.png' %}" alt="error">
                </i>
            </label>
            <ul class="menu">
                <li><a href="{% url 'home' %}">Inicio</a></li>
                <li><a href="{% url 'hombre' %}">Hombres</a></li>
                <li><a href="{% url 'mujer' %}">Mujer</a></li>
                <li><a href="{% url 'contacto' %}">Contactos</a></li>

                {% if user.is_authenticated %}

                <li>
                    <a href="{% url 'logout' %}">Cerrar sesión</a>
                </li>
                <li>
                    <a href="#">@{{ user.username }}</a>
                </li>
                {% else %}

                <li>
                    <a href="{% url 'login' %}">Iniciar sesión</a>
                </li>

                <li>
                    <a href="{% url 'registro' %}">Registrarse</a>
                </li>
                {% endif %}

            </ul>
        </div>

    </nav>
</header>

<body>
    <h1 style="margin-top: 150px; margin-left: 20px; margin-bottom: 12px;">Contactos</h1>

    <p style="margin-left: 20px;">¡Gracias por visitarnos! Si tienes alguna pregunta o comentario, no dudes en ponerte
        en contacto con nosotros.
        Estamos aquí para ayudarte.</p>

    <address style="margin: 20px;">
        <h2>Detalles de contacto:</h2>
        <p>Correo electrónico: info@tutienda.com</p>
        <p>Teléfono: (123) 456-7890</p>
        <p>Dirección: Avenida Manabí, Portoviejo, Ecuador</p>
    </address>

    <p style="margin-left: 20px; font-size: 20px;">¡Esperamos saber de ti pronto!</p>

    <!-- Agrega más contenido según sea necesario -->

</body>

</html>

Tienda/templates/Tienda/home.html
{% extends 'Tienda/base.html' %}
{% block title %} Pagina Principal | Mi sitio web {% endblock %}

{% block content %}
<!-- Mostrar lista de Productos -->
<h1>Productos Disponibles</h1>
<section class="productos">
    {% for producto in productos %}
    <article>
        <h3>{{ producto.nombre }}</h3>
        <p>
            {{ producto.descripcion }}
        </p>

        {% if producto.imagen %}
        <img src="{{ producto.imagen.url }}" alt="">
        {% else %}
        <p>No hay imagen disponible</p>
        {% endif %}

        <div class="precio">
            <button><a style="text-decoration: none;color: #000;" href="{% url 'compra' %}">Pedido</a></button>
            <h3>$ {{ producto.precio }}</h3>
        </div>
    </article>
    {% endfor %}
</section>

{% endblock %}

Tienda/templates/compra/compra.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Compra de Producto</title>
    <link rel="stylesheet" href="{% static 'Tienda/css/compra.css' %}">

</head>

<body>


    <h1>Realizar Pedido</h1>
    <div>

        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
        </ul>
        {% endif %}

        <form method="post" action="{% url 'compra' %}">
            {% csrf_token %}

            <label for="id_nombre">Nombre:</label>
            <input type="text" name="nombre" id="id_nombre" required>

            <label for="id_email">Correo Electrónico:</label>
            <input type="email" name="email" id="id_email" required>

            <label for="id_direccion">Dirección de Envío:</label>
            <input type="text" name="direccion" id="id_direccion" required>

            <label for="id_telefono">Teléfono:</label>
            <input type="tel" name="telefono" id="id_telefono" required>

            <label for="id_cantidad">Cantidad a comprar:</label>
            <input type="number" name="cantidad" id="id_cantidad" min="1" required>

            <br>
            <div class="lin">
                <ul class="lint-items">
                    <li><a href="{% url 'home' %}">Inicio</a></li>
                </ul>
                {% if user.is_authenticated %}
                <button type="submit">Pedido</button>
                {% else %}
                <p>Inicia sesión para comprar</p>
                <a href="{% url 'login' %}">Iniciar sesión</a>
                {% endif %}
            </div>


        </form>
    </div>

</body>

</html>

Tienda/templates/ropa/hombre.html
{% extends 'Tienda/base.html' %}
{% load static %}

{% block title %} Pagina Principal | Mi sitio web {% endblock %}

{% block extra_styles %} 
<link rel="stylesheet" href="{% static 'Tienda/css/ropa.css' %}">
<!-- <link rel="stylesheet" href="{% static 'Tienda/css/productos.css' %}"> -->
{% endblock %}

{% block content %}
    <!-- Mostrar lista de Productos -->
    <h1>Productos para Hombres</h1>
    <section class="productos">
        {% for elemento in productos %}
            {% if elemento.genero == 'H' %}
                <article>
                    <h3>{{ elemento.nombre }}</h3>
                    <p>{{ elemento.descripcion }}</p>
                    {% if elemento.imagen %}
                        <img src="{{ elemento.imagen.url }}" alt="">
                    {% else %}
                        <p>No hay imagen disponible</p>
                    {% endif %}
                    <div class="precio">
                        <button><a style="text-decoration: none;color: #000;" href="{% url 'compra' %}">Pedido</a></button>
                        <h3>$ {{ elemento.precio }}</h3>
                    </div>
                </article>
            {% endif %}
        {% endfor %}
    </section>

{% endblock %}

Tienda/templates/ropa/mujer.html
{% extends 'Tienda/base.html' %}
{% load static %}

{% block title %} Pagina Principal | Mi sitio web {% endblock %}

{% block extra_styles %}
<link rel="stylesheet" href="{% static 'Tienda/css/ropa.css' %}">
<link rel="stylesheet" href="{% static 'Tienda/css/productos.css' %}">
{% endblock %}

{% block content %}
<!-- Mostrar lista de Productos -->
<h1 style="margin: 150px;">Productos para Mujeres</h1>
<section class="productos">
    {% for elemento in productos %}
    {% if elemento.genero == 'M' %}
    <article>
        <h3>{{ elemento.nombre }}</h3>
        <p>{{ elemento.descripcion }}</p>
        {% if elemento.imagen %}
        <img src="{{ elemento.imagen.url }}" alt="">
        {% else %}
        <p>No hay imagen disponible</p>
        {% endif %}
        <div class="precio">
            <button><a style="text-decoration: none;color: #000;" href="{% url 'compra' %}">Pedido</a></button>
            <h3>$ {{ elemento.precio }}</h3>
        </div>
    </article>
    {% endif %}
    {% endfor %}
</section>

{% endblock %}